### ISSUE TITLE
Problem with keyboard and chameleon_io module on V2 hardware and C64C

### ISSUE THREAD

**Issue by robinsonb5** [pwsoft/fpga_examples#3]
I have a problem with the IO module and keyboard scanning on V2 hardware which shows up in both the hwtest core and my not-yet-functional port of the Minimig core, when connected to my C64C.  This manifests both with a flashed .rbf binary downloaded from forum.icomp.de and with a self-built .sof flashed via USB Blaster.

In the HWTest core the keyboard grid is mostly stable white, but the squares on the diagonal from top left to bottom right are flickering to black, I'd estimate about 5-10% of the time.
When pressing a key on the C64 keyboard the respective square goes black, but only those on the diagonal are stable black.  The others are flickering to white, at about the same rate as mentioned previously.

I get no response from the restore key.

Joysticks seem to be OK, though on one occasion I saw the leftmost bit (2nd fire button) corresponding to the C64's inbuilt joysticks flicker.

The keyboard seems to work fine with the Chameleon C64 core, however.

**Comment by pwsoft** [comment]
The hardware test won't show the state of the restore key on the C64 keyboard. This test item only works when a keyboard is connected to the docking-station.
I'm aware of some V2 issues related to keyboard scanning. One user reported similar issues for the VIC-20 core. And we have one test machine that shows similar behavior. I was not able to reproduce the problem myself (yet). So debugging this issue is a little tricky.

**Comment by robinsonb5** [comment]
Glad to hear it's not just me.  I've added the JTAG header, and can use SignalTap, so if there are any tests I can usefully conduct just let me know.

**Comment by pwsoft** [comment]
Fixed
